export const list = [
  {
    index: "1",
    year: "2025",
    campusName: "江湾校区",
    build: "江湾主校区-食堂",
    project: "江湾校区老食堂2、3楼漏水维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "江-2025-035",
    projectAmount: "6.91 ",
    constructionUnit: "复豪建设",
    repairParts: "二楼大厅，三楼阳光棚",
    mainJobContent: "阳光棚防水维修",
    commencementDate: "2025-09-04",
    completionDate: "2025-09-20",
    remarks: "",
    projectStatus: "已竣工",
  },
  {
    index: "2",
    year: "2025",
    campusName: "江湾校区",
    build: "江湾主校区-食堂",
    project: "江湾校区食堂一楼后厨、小厅漏水维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "江-2025-026",
    projectAmount: "8.71 ",
    constructionUnit: "复豪建设",
    repairParts: "一楼后厨、小厅",
    mainJobContent: "室内过道，出餐口处防水",
    commencementDate: "2025-06-20",
    completionDate: "2025-07-15",
    remarks: "",
    projectStatus: "已竣工",
  },
  {
    index: "3",
    year: "2025",
    campusName: "枫林校区",
    build: "枫林护理学院-护理学院4号楼",
    project: "枫林校区护理学院4号楼学生宿舍整修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "枫-2025-046",
    projectAmount: "40.04 ",
    constructionUnit: "复豪建设",
    repairParts: "4号楼学生宿舍外墙、屋顶",
    mainJobContent: "外墙、屋顶防水维修",
    commencementDate: "2025-08-15",
    completionDate: "2025-09-30",
    remarks: "",
    projectStatus: "已竣工",
  },
  {
    index: "4",
    year: "2025",
    campusName: "邯郸校区",
    build: "邯郸本部-第三教学楼",
    project: "邯郸校区北校区部分楼宇台风漏水维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "邯-2025-116",
    projectAmount: "8.99 ",
    constructionUnit: "复豪建设",
    repairParts: "北校区部分楼宇台风",
    mainJobContent: "防水维修",
    commencementDate: "2025-09-18",
    completionDate: "2025-10-13",
    remarks: "",
    projectStatus: "已竣工",
  },
  {
    index: "5",
    year: "2025",
    campusName: "邯郸校区",
    build: "环境科学楼",
    project: "邯郸校区环境科学楼104C隔壁辐射防护委员会办公室顶漏水维修工程",
    applyDepartment: "实验室安全管理中心",
    projectApprovalNumber: "",
    projectAmount: "",
    constructionUnit: "复豪建设",
    repairParts: "104C隔壁辐射防护委员会办公室",
    mainJobContent: "屋顶防水维修",
    commencementDate: "",
    completionDate: "",
    remarks: "",
    projectStatus: "立项",
  },
  {
    index: "6",
    year: "2025",
    campusName: "邯郸校区",
    build: "邯郸本部-环境工程系2号楼",
    project: "邯郸校区环境楼屋顶部渗水维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "",
    projectAmount: "",
    constructionUnit: "复豪建设",
    repairParts: "2号楼",
    mainJobContent: "屋顶防水维修",
    commencementDate: "",
    completionDate: "",
    remarks: "",
    projectStatus: "立项",
  },
  {
    index: "7",
    year: "2025",
    campusName: "枫林校区",
    build: "枫林西苑-图书馆",
    project: "枫林校区图书馆14楼卫生间门口顶部楼漏水维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "枫-2025-054",
    projectAmount: "2.44 ",
    constructionUnit: "复豪建设",
    repairParts: "14楼卫生间门口",
    mainJobContent: "卫生间防水修缮",
    commencementDate: "2025-09-10",
    completionDate: "2025-09-25",
    remarks: "",
    projectStatus: "已竣工",
  },
  {
    index: "8",
    year: "2025",
    campusName: "邯郸校区",
    build: "邯郸东区-新闻学院图书馆",
    project: "邯郸校区新闻学院图书楼顶漏水维修工程",
    applyDepartment: "新闻学院",
    projectApprovalNumber: "邯-2025-110",
    projectAmount: "12.79 ",
    constructionUnit: "复豪建设",
    repairParts: "图书馆顶",
    mainJobContent: "屋顶防水维修",
    commencementDate: "2025-09-15",
    completionDate: "2025-10-10",
    remarks: "",
    projectStatus: "已竣工",
  },
  {
    index: "9",
    year: "2025",
    campusName: "邯郸校区",
    build: "邯郸本部-理科图书馆",
    project: "邯郸校区理科图书馆202阅览室窗顶渗漏维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "邯-2025-115",
    projectAmount: "15.08 ",
    constructionUnit: "复豪建设",
    repairParts: "202阅览室窗顶",
    mainJobContent: "屋顶防水维修",
    commencementDate: "",
    completionDate: "",
    remarks: "",
    projectStatus: "立项",
  },
  {
    index: "10",
    year: "2025",
    campusName: "枫林校区",
    build: "枫林西苑-西20号楼",
    project: "枫林校区西20-21号楼部分宿舍卧室及卫生间漏水维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "枫-2025-029",
    projectAmount: "21.08 ",
    constructionUnit: "复豪建设",
    repairParts: "部分房间",
    mainJobContent: "卫生间防水修缮",
    commencementDate: "2025-08-10",
    completionDate: "2025-09-05",
    remarks: "",
    projectStatus: "已竣工",
  },
  {
    index: "11",
    year: "2025",
    campusName: "江湾校区",
    build: "江湾主区-发育生物学研究所",
    project: "江湾校区发育所、图书馆电梯机房渗水维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "",
    projectAmount: "",
    constructionUnit: "台丰实业",
    repairParts: "电梯机房屋面及外墙",
    mainJobContent: "屋面、外墙防水修缮",
    commencementDate: "",
    completionDate: "",
    remarks: "发育所、图书馆",
    projectStatus: "立项",
  },
  {
    index: "12",
    year: "2025",
    campusName: "邯郸校区",
    build: "邯郸南区-南区食堂",
    project: "邯郸校区南区学生食堂3楼活动中心东侧门口渗水维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "邯-2025-119",
    projectAmount: "0.91 ",
    constructionUnit: "台丰实业",
    repairParts: "3楼屋面、伸缩缝",
    mainJobContent: "屋面、伸缩缝防水修缮",
    commencementDate: "",
    completionDate: "",
    remarks: "",
    projectStatus: "立项",
  },
  {
    index: "13",
    year: "2025",
    campusName: "枫林校区",
    build: "枫林西苑-保卫处",
    project: "枫林校区保卫处2楼西侧办公室渗水维修工程",
    applyDepartment: "保卫处",
    projectApprovalNumber: "",
    projectAmount: "",
    constructionUnit: "台丰实业",
    repairParts: "2楼西侧屋面、地面",
    mainJobContent: "屋面、地面防水修缮",
    commencementDate: "",
    completionDate: "",
    remarks: "",
    projectStatus: "立项",
  },
  {
    index: "14",
    year: "2025",
    campusName: "邯郸校区",
    build: "邯郸北区-北区91号楼",
    project: "邯郸校区北区学生公寓91号楼302室、亚青2号楼地下室渗水维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "",
    projectAmount: "",
    constructionUnit: "台丰实业",
    repairParts: "卫生间地面、地下室墙面",
    mainJobContent: "地面、墙面防水修缮",
    commencementDate: "",
    completionDate: "",
    remarks: "北区91号楼、亚青2号楼",
    projectStatus: "立项",
  },
  {
    index: "15",
    year: "2025",
    campusName: "邯郸校区",
    build: "邯郸南区-南区宿舍二期20号楼",
    project: "邯郸校区南区20号楼2楼卫生间渗水维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "邯-2025-117",
    projectAmount: "2.01 ",
    constructionUnit: "台丰实业",
    repairParts: "卫生间地面",
    mainJobContent: "地面防水修缮",
    commencementDate: "",
    completionDate: "",
    remarks: "",
    projectStatus: "立项",
  },
  {
    index: "16",
    year: "2025",
    campusName: "邯郸校区",
    build: "邯郸南区-南区游泳馆",
    project: "邯郸校区南区游泳馆乒乓房配电间渗水维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "",
    projectAmount: "",
    constructionUnit: "台丰实业",
    repairParts: "2楼淋浴间墙面",
    mainJobContent: "更换给水管线",
    commencementDate: "",
    completionDate: "",
    remarks: "",
    projectStatus: "立项",
  },
  {
    index: "17",
    year: "2025",
    campusName: "邯郸校区",
    build: "邯郸南区-南区宿舍二期33号楼",
    project: "邯郸校区南区33号楼楼梯间外墙渗水维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "邯-2025-103",
    projectAmount: "2.15 ",
    constructionUnit: "台丰实业",
    repairParts: "楼梯间外墙、屋面",
    mainJobContent: "屋面、外墙防水修缮",
    commencementDate: "",
    completionDate: "",
    remarks: "",
    projectStatus: "立项",
  },
  {
    index: "18",
    year: "2025",
    campusName: "邯郸校区",
    build: "邯郸北区-北区19号楼",
    project: "邯郸校区北区学生公寓19、55、91、92、93、103、107、112、121号楼渗水维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "邯-2025-097",
    projectAmount: "45.79 ",
    constructionUnit: "台丰实业",
    repairParts: "屋面、外墙、卫生间地面",
    mainJobContent: "屋面、外墙、卫生间修缮",
    commencementDate: "2025-09-05",
    completionDate: "2025-10-14",
    remarks: "北区19、55、91、92、93、103、107、112、121号楼",
    projectStatus: "已竣工",
  },
  {
    index: "19",
    year: "2025",
    campusName: "枫林校区",
    build: "枫林西苑-书院楼",
    project: "枫林校区书院楼东楼多个宿舍卫生间、阳台墙顶面漏水维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "枫-2025-042",
    projectAmount: "44.73 ",
    constructionUnit: "台丰实业",
    repairParts: "部分房间",
    mainJobContent: "卫生间防水修缮",
    commencementDate: "2025-09-05",
    completionDate: "2025-09-29",
    remarks: "",
    projectStatus: "已竣工",
  },
  {
    index: "20",
    year: "2025",
    campusName: "江湾校区",
    build: "江湾主区-生科楼",
    project: "江湾校区生科院F区报告厅配电间屋面渗水维修工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "江-2025-029",
    projectAmount: "10.25 ",
    constructionUnit: "台丰实业",
    repairParts: "配电间平台屋面",
    mainJobContent: "屋面、外墙防水修缮",
    commencementDate: "2025-09-05",
    completionDate: "2025-09-29",
    remarks: "",
    projectStatus: "已竣工",
  },
  {
    index: "21",
    year: "2025",
    campusName: "江湾校区",
    build: "江湾主区-图书馆",
    project: "江湾校区李兆基图书馆玻璃顶棚漏水修缮工程",
    applyDepartment: "图书馆",
    projectApprovalNumber: "",
    projectAmount: "",
    constructionUnit: "东岗建设",
    repairParts: "玻璃顶棚",
    mainJobContent: "玻璃顶棚防水修缮",
    commencementDate: "",
    completionDate: "",
    remarks: "",
    projectStatus: "立项",
  },
  {
    index: "22",
    year: "2025",
    campusName: "邯郸校区",
    build: "邯郸本部-理科图书馆",
    project: "邯郸校区理科图书馆后花园西面连廊雨棚漏水修缮工程",
    applyDepartment: "图书馆",
    projectApprovalNumber: "",
    projectAmount: "",
    constructionUnit: "东岗建设",
    repairParts: "西面连廊雨棚",
    mainJobContent: "雨棚防水修缮",
    commencementDate: "",
    completionDate: "",
    remarks: "",
    projectStatus: "立项",
  },
  {
    index: "23",
    year: "2025",
    campusName: "邯郸校区",
    build: "邯郸南区-南区宿舍二期30号楼",
    project: "邯郸校区南区学生公寓30号楼520室屋面漏水修缮工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "",
    projectAmount: "",
    constructionUnit: "东岗建设",
    repairParts: "南区30号楼520室",
    mainJobContent: "屋面防水修缮",
    commencementDate: "",
    completionDate: "",
    remarks: "",
    projectStatus: "立项",
  },
  {
    index: "24",
    year: "2025",
    campusName: "枫林校区",
    build: "枫林东苑-二号医学科研楼",
    project: "枫林校区2号科研楼公共区域及室内19处漏水修缮工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "",
    projectAmount: "",
    constructionUnit: "东岗建设",
    repairParts: "部分公区及室内",
    mainJobContent: "外墙屋面等防水修缮",
    commencementDate: "",
    completionDate: "",
    remarks: "二号科研楼A、B座",
    projectStatus: "立项",
  },
  {
    index: "25",
    year: "2025",
    campusName: "张江校区",
    build: "张江校区二期-化学南楼",
    project: "张江校区化学南楼400室屋面漏水修缮工程",
    applyDepartment: "药学院",
    projectApprovalNumber: "",
    projectAmount: "",
    constructionUnit: "东岗建设",
    repairParts: "400室屋面",
    mainJobContent: "屋面防水修缮",
    commencementDate: "",
    completionDate: "",
    remarks: "",
    projectStatus: "立项",
  },
  {
    index: "26",
    year: "2025",
    campusName: "江湾校区",
    build: "江湾主区-环境科学楼",
    project: "江湾校区环科楼地下室两处漏水及电梯机房排水管漏水修缮工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "",
    projectAmount: "",
    constructionUnit: "东岗建设",
    repairParts: "局部地下室",
    mainJobContent: "注浆防水",
    commencementDate: "",
    completionDate: "",
    remarks: "",
    projectStatus: "立项",
  },
  {
    index: "27",
    year: "2025",
    campusName: "张江校区",
    build: "张江北区-二教",
    project: "张江校区第二教学楼2404室屋面及东外墙漏水修缮工程",
    applyDepartment: "微电子学院",
    projectApprovalNumber: "张-2025-018",
    projectAmount: "5.41 ",
    constructionUnit: "东岗建设",
    repairParts: "局部屋面外墙",
    mainJobContent: "屋面外墙防水修缮",
    commencementDate: "",
    completionDate: "",
    remarks: "",
    projectStatus: "立项",
  },
  {
    index: "28",
    year: "2025",
    campusName: "张江校区",
    build: "张江南区-科研楼",
    project: "张江校区科研楼西辅楼208室漏水修缮工程",
    applyDepartment: "药学院",
    projectApprovalNumber: "",
    projectAmount: "",
    constructionUnit: "东岗建设",
    repairParts: "208室屋面",
    mainJobContent: "屋面防水修缮",
    commencementDate: "",
    completionDate: "",
    remarks: "",
    projectStatus: "立项",
  },
  {
    index: "29",
    year: "2025",
    campusName: "张江校区",
    build: "变电站2",
    project: "张江校区二期变电站屋面漏水修缮工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "张-2025-016",
    projectAmount: "6.14 ",
    constructionUnit: "东岗建设",
    repairParts: "屋面",
    mainJobContent: "屋面防水修缮",
    commencementDate: "2025-08-28",
    completionDate: "2025-09-11",
    remarks: "二期变电站",
    projectStatus: "已竣工",
  },
  {
    index: "30",
    year: "2025",
    campusName: "江湾校区",
    build: "江湾主区-二号交叉学科楼",
    project: "江湾校区二号交叉学科楼E1023会议室漏水修缮工程",
    applyDepartment: "总务处",
    projectApprovalNumber: "江-2025-036",
    projectAmount: "4.88 ",
    constructionUnit: "东岗建设",
    repairParts: "幕墙",
    mainJobContent: "幕墙防水修缮",
    commencementDate: "2025-09-14",
    completionDate: "2025-09-23",
    remarks: "",
    projectStatus: "已竣工",
  },
];
